stages:
  - build
  - test
  - publish

image: node:24-alpine

build-packages:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

test:
  stage: test
  script:
    - npm install
    - |
      cd src/samples
      npm install
      cd ../../
    - npm run lint
    - npm test

sonarqube-static-analysis:
  stage: test
  needs: []
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - ct-registry/.sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

publish:
  stage: publish
  before_script:
    - apk add --no-cache jq
  script:
    - |
      VERSION=$(jq -r '.version' package.json)
      BRANCH_VERSION="${VERSION}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
      echo "Publishing version $BRANCH_VERSION as @facultyai/a2a-js"
      contents=$(jq '.name = "@facultyai/a2a-js"' package.json)
      echo "$contents" > package.json
      npm version $BRANCH_VERSION
    - npm publish
